config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  
  get 'static_pages/home'
  get 'static_pages/about'
  # get 'notes/index'
  # get 'notes/show'
  # get 'notes/new'

  resources :notes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(notes_params)
 
    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end

  def edit 
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(notes_params)
      redirect_to notes_path
    else
      render :edit
    end 
  end 

  def destroy
    Note.find(params[:id]).destroy
    redirect_to notes_path
  end
 
  private
 
    def notes_params
      params.require(:note).permit(:title, :author, :body)
    end
end

app/controllers/static_notes_controller.rb
class StaticNotesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/static_notes_helper.rb
module StaticNotesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_navbar.html.erb
<div style="background-color: gray; display: flex; justify-content: space-around; padding: 8px 16px 8px 16px">
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Notes', notes_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostItNotes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/index.html.erb
<div style= "text-align: center">
<h1> Notes </h1>

<%= link_to 'New Note', new_note_path %>

<% @notes.each do |note| %> 
  <h2><%= note.title %></h2>
<%= link_to 'Show Note', note_path(note) %>
<%= link_to 'Edit Note', edit_note_path(note) %>
<%= link_to 'Destroy Note', note, method: :delete %>
<% end %>
</div>

app/views/notes/new.html.erb
<h1>New Note</h1>
<%= form_for @note do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/notes/show.html.erb
<div style='background-color:yellow; max-width: 200px; margin: 0 auto; box-shadow:  10px 10px 8px #888888; text-align: center'>
<h1><%= @note.title %></h1>
<h4><%= @note.author %></h1>
<p><%= @note.body %></p>
<%= link_to 'Back', notes_path %>
</div>

app/views/static_notes/about.html.erb
<h1>StaticNotes#about</h1>
<p>Find me in app/views/static_notes/about.html.erb</p>

app/views/static_notes/home.html.erb
<h1>StaticNotes#home</h1>
<p>Find me in app/views/static_notes/home.html.erb</p>

app/views/static_pages/about.html.erb
<div style="text-align:center">
<h1>About</h1>
<p>We make post it notes</p>
</div>

app/views/static_pages/home.html.erb
<div style='text-align:center'>
<h1>Notes Home</h1>
<p> Welcome to the post it note maker </p>
</div>